spring.application.name=MillenniumComics
spring.datasource.url=jdbc:postgresql://db.xtukgjnnxkntkqalqlsi.supabase.co:5432/postgres?user=postgres&password=VAxqCDB2DcveJ9Os
spring.datasource.username=postgres
spring.datasource.password=VAxqCDB2DcveJ90s
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
