spring.application.name=MillenniumComics
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=postgres.xtukgjnnxkntkqalqlsi
spring.datasource.password=VAxqCDB2DcveJ9Os