spring.application.name=MillenniumComics
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?user=postgres.xtukgjnnxkntkqalqlsi&password=VAxqCDB2DcveJ9Os
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true